name: create_release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: windows-latest
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: cargo build --release
      - name: create_build
        run: |
          gh release create "${{ env.VERSION }}" --title "${{ env.VERSION }}" --generate-notes
          gh release upload "${{ env.VERSION }}" "target/release/test_module.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}